### PR TITLE
allow to specify list of excluded dirs from watching

### PR DESCRIPTION
**Pull request by sergeyt**

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks your PR!

Code looks good to me, just wonder why not just add a `ignores` section in `.bra.toml`?

Update: I know `*ignore` is kind of some convention, just wonder :smile:

**Comment by sergeyt** [comment]
At that moment when I made this PR I thought about only `*ignore` convention - this is the only the reason why I did this way :smile: Also I thought that `.gitignore` could be used as default ignore list if  custom list is not specified.

`ignore` section in `.bra.toml` is ok too since it performs the same task. Lets use `ignore` section instead if `.braignore` looks needless and redundant. I'll update the PR soon.

**Comment by unknwon** [comment]
OK, no problem! :smile:

**Comment by sergeyt** [comment]
@Unknwon I've updated the PR.

**Comment by unknwon** [comment]
Looks all good! :beer:

Would you mind change `ignore` to `ignores`? Or you think `ignore` is better name?

**Comment by sergeyt** [comment]
`ignore` is economically shorter :smile: and looks more canonical and isomorphic, e.g. `.gitignore` has no `s` morphism

**Comment by unknwon** [comment]
Cool, merging, thanks again!

**Pull request merged**
